### ISSUE TITLE
Update server exestiert nicgt .-.

### ISSUE THREAD

**Issue by LetsPlayNik** [PoloCloud-official/cloudsystem#7]
Naja man kann eure cloud schlecht nutzen wenn ihr die falschen update server angegeben habt weil die ip nicht erreichbar ist XD

**Comment by HttxMarco** [comment]
Wir haben den "alten" Update server heruntergefahren. Ab Samstag sollte ein neuer online sein, welche für die Beta dann 100% funktionabel ist.
