### ISSUE TITLE
Vorschlag - Update Server

### ISSUE THREAD

**Issue by WhitqFlorian** [PoloCloud-official/cloudsystem#8]
Würde mir für die PoloCloud wünschen das man die Cloud auch ohne den Update Server verwenden kann bzw. das man selber einstellen kann ob der update server verwendet werden soll oder nicht.

**Comment by iPommes** [comment]
Hey, wurde in https://github.com/PoloCloud-official/cloudsystem/commit/60302a9706ee77cb5680c71d51ac2a052546bf62 implementiert.
